spring:
  application:
    name: Gray-Pants
    portone:
      api-key: PORTONE_API_KEY
      api-secret: PORTONE_API_SECRET
      user-code: PORTONE_USER_CODE
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  profiles:
    include: oauth, mail, s3
  data:
    redis:
      host: localhost
      port: 6379
    include: oauth
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  session:
    store-type: redis

server:
  port: 8080

springdoc:
  packages-to-scan: com.poku.graypants
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

