spring:
  application:
    name: Gray-Pants
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    datasource:
      url: jdbc:h2:tcp://localhost/~/graypants
      username: sa
    h2:
      console:
        enabled: true
  profiles:
    include: oauth